version: "3.0"
services:
  elasticsearch:
    image: elasticsearch:8.3.3
    container_name: es-container
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS="-Xms256m -Xmx256m"
      - xpack.security.enabled=false
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - elastic

  kibana:
    image: kibana:8.3.3
    environment:
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elastic      

networks:
  elastic:
    driver: bridge
